### PR TITLE
Minor updates

### LINKED ISSUE #15: Minor updates
When running PHPUnit there were 6 risky tests:

```
1) Fusions\Test\Monolog\LogDna\Formatter\BasicJsonFormatterTest::test_format
This test does not have a @covers annotation but is expected to have one

2) Fusions\Test\Monolog\LogDna\Formatter\SmartJsonFormatterTest::test_format
This test does not have a @covers annotation but is expected to have one

3) Fusions\Test\Monolog\LogDna\Formatter\SmartJsonFormatterTest::test_format_ignore_paths
This test does not have a @covers annotation but is expected to have one

4) Fusions\Test\Monolog\LogDna\Formatter\SmartJsonFormatterTest::test_limit_long_traces
This test does not have a @covers annotation but is expected to have one

5) Fusions\Test\Monolog\LogDna\Handler\LogDnaHandlerTest::test_write
This test does not have a @covers annotation but is expected to have one

6) Fusions\Test\Monolog\LogDna\Handler\LogDnaHandlerTest::test_shorten_long_exceptions
This test does not have a @covers annotation but is expected to have one

OK, but incomplete, skipped, or risky tests!
Tests: 6, Assertions: 50, Risky: 6.
```
- [x] See if we can eliminate the riskiness!
- [x] Remove deprecated `setStackTraceLimit()` (no comment/clue as to why)
- [x] Create a new major release

**Estimate: 2hrs**

### PR DESCRIPTION
**Pull request by WillJW**
Closes #15

### CODE REVIEW

**Review by ziadoz — APPROVED** [review]

**Review by weshooper — APPROVED** [review]

File: src/Formatter/SmartJsonFormatter.php [hunk 1]
```diff
@@ -19,15 +18,6 @@ public function setIgnorePaths(array $ignorePaths): void
         $this->ignorePaths = $ignorePaths;
     }
 
-    /**
-     * @deprecated
-     * To limit the size of the output you can set a stack trace limit.
-     */
-    public function setStackTrackLimit(int $limit): void
```
Comment (weshooper) [inline src/Formatter/SmartJsonFormatter.php:26]: Only just spotted the typo! 😆
